---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
github_id:   "doracle-org"
github_repo: "Doracle"

title:       "Doracle"
keywords:    "Decentralized Oracle Service for Smart Contracts"
description: "Doracle : Decentralized Oracle Service for Smart Contracts"

source_link: "https://github.com/doracle-org/Doracle"

favicon:     "img/favicon.ico"
touch_icon:  "img/apple.png"
# google_analytics_key: UA-000000-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#ED7950'
  turquoise: '#0fbfcf'
  silver:    '#D0D0D0'
  darkgreen: '#4F7C80'
  cobalt:    '#3035A4'

kramdown:
  auto_ids:  false

